import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Toaster } from "@/components/ui/toaster";
import { ToastProvider } from "@/context/ToastContext";
import { QueryProvider } from "@/providers/QueryProvider";
import { GlobalRouteLoading } from "@/components/common/GlobalRouteLoading";
import { SocketProvider } from "@/context/SocketProvider";

const locales = ["en"];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  //@ts-ignore
  const messages = await getMessages(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <SocketProvider>
            <QueryProvider>
              <ThemeProvider>
                <ToastProvider>
                  <Toaster />
                  <GlobalRouteLoading />
                  {children}
                </ToastProvider>
              </ThemeProvider>
            </QueryProvider>
          </SocketProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
